### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by brunoklein99** [Phylliida/PyTorchWindowsBinary#1]
I am getting the following error:

```
C:\Users\klein-desk\AppData\Local\Programs\Python\Python35\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.1\helpers\pycharm\_jb_unittest_runner.py" --path G:/Source/pytorch-examples/mnist/main.py
Testing started at 2:29 PM ...
Launching unittests with arguments python -m unittest G:/Source/pytorch-examples/mnist/main.py in G:\Source\pytorch-examples\mnist






Error
Traceback (most recent call last):
  File "C:\Users\klein-desk\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 58, in testPartExecutor
    yield
  File "C:\Users\klein-desk\AppData\Local\Programs\Python\Python35\lib\unittest\case.py", line 600, in run
    testMethod()
  File "C:\Users\klein-desk\AppData\Local\Programs\Python\Python35\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: main
Traceback (most recent call last):
  File "C:\Users\klein-desk\AppData\Local\Programs\Python\Python35\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "G:\Source\pytorch-examples\mnist\main.py", line 3, in <module>
    import torch
  File "C:\Users\klein-desk\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\__init__.py", line 41, in <module>
    from torch._C import *
ImportError: DLL load failed: %1 is not a valid Win32 application.




Ran 1 test in 0.002s

FAILED (errors=1)

Process finished with exit code 1

```

This is Windows x64 with Python x64 as well. Keras/Tensorflow work fine with CUDA.

**Comment by Phylliida** [comment]
It looks like your folder says Python 3.5 but just to check what version of python are you on?

**Comment by brunoklein99** [comment]
That was 3.5 really, but I just installed Anaconda with 3.6 and then installed peterjc123's package.

**Comment by Phylliida** [comment]
Okay I found the issue! Some of my dlls (lapack and TH.dll) weren't put into my pip wheel for some reason. I uploaded them to this repo, just put them into <pythondir>/lib/site-packages/torch/lib

**Comment by HarishKumarKR1** [comment]
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import cv2

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import cv2
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by Phylliida** [comment]
I recommend using peterjc123's package and not this, it should work better for you
