### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by shaohui139** [Phylliida/PyTorchWindowsBinary#3]
Hello，i am getting the following error:

"C:\Program Files\Python35\python.exe" E:/GitHub/VerificationCode/sceneReco/demo.py
Traceback (most recent call last):
  File "E:/GitHub/VerificationCode/sceneReco/demo.py", line 3, in <module>
    from crnnport import *
  File "E:\GitHub\VerificationCode\sceneReco\crnnport.py", line 6, in <module>
    import torch
  File "C:\Program Files\Python35\lib\site-packages\torch\__init__.py", line 41, in <module>
    from torch._C import *
ImportError: DLL load failed: 找不到指定的模块。

Process finished with exit code 1

How can i fix the problem?
        Thanks

Python version: 3.5.2
Operating system:Win 10

![error](https://user-images.githubusercontent.com/775830/32649665-dbd56e14-c635-11e7-924d-413b29dedc28.png)

**Comment by Phylliida** [comment]
I'm not sure, I'd recommend installing peterjc123's package instead honestly I didn't know about his when I made mine and his seems to work better
